subjects_homepage:
    pattern:  /tantargyak/
    defaults: { _controller: FrontendSubjectBundle:Default:index }

get_all_subject:
    pattern:  /tantargyak/tantargyak-lekerdezese
    defaults: { _controller: FrontendSubjectBundle:Default:getAllSubjects }

subjects_homepage_as_one_subject:
    pattern:  /tantargyak/tantargy/{subject}.html
    defaults: { _controller: FrontendSubjectBundle:Default:index }

get_upload_window:
    pattern:  /tantargyak/fajl-feltolto-ablak-lekerdezes
    defaults: { _controller: FrontendSubjectBundle:Upload:getUploadWindow }

upload_files:
    pattern:  /ajax/fajl-feltoltes/
    defaults: { _controller: FrontendSubjectBundle:Upload:uploadFile }

upload_one_file_ajax:
    pattern:  /tantargyak/ajax/fajl-feltoltes/
    defaults: { _controller: FrontendSubjectBundle:Upload:uploadOneFile }

update_files_subjects:
    pattern:  /tantargyak/ajax/file-feltoltes/tantargyak-modositasa/
    defaults: { _controller: FrontendSubjectBundle:Upload:updateSubjects }

file_single:
    pattern:  /feltoltott-fajlok/{fileid}
    defaults: { _controller: FrontendSubjectBundle:Default:singleFile }

file_download:
    pattern:  /feltoltott-fajlok/{fileid}/letoltes
    defaults: { _controller: FrontendSubjectBundle:Default:fileDownload }
    
