parameters:
#    frontend_subject.example.class: Frontend\SubjectBundle\Example

services:
     frontend.twig.subject_extension:
        class: Frontend\SubjectBundle\Twig\SubjectExtension
        tags:
            - { name: twig.extension }
