parameters:
#    frontend_subject.example.class: Frontend\SubjectBundle\Example

services:
#    frontend_subject.example:
#        class: %frontend_subject.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
