generator: admingenerator.generator.doctrine
params:
    model: Frontend\DocsBundle\Entity\Docs
    namespace_prefix: Frontend
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: 
        name :
            label: Név
        text:
            label : Szöveg
            addFormOptions:
                        attr: 
                            class: addCkEditor
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Dokumentumok a jegyzetbázison
            display: [name]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Új dokumentum létrehozása
            display: [name, text]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "A \"%object%\" nevű dokumentum szerkesztése|{ %object%: Docs.name }|"
            display: [name, text]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Docs.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
