admin_page_subjects:
    resource: "@FrontendAdminBundle/Controller/Subjects/"
    type:     admingenerator
    prefix:   /admin/oldal/tantargyak
    
admin_login:
    pattern:  /admin
    defaults: { _controller: FrontendAdminBundle:Default:login }
    
admin_list:
    pattern:  /admin/lista
    defaults: { _controller: FrontendAdminBundle:Default:list }
