admin_page_subjects:
    resource: "@FrontendAdminBundle/Controller/Subjects/"
    type:     admingenerator
    prefix:   /admin/oldal/tantargyak
    
admin_page_docs:
    resource: "@FrontendAdminBundle/Controller/Docs/"
    type:     admingenerator
    prefix:   /admin/oldal/dokumentumok

admin_page_UserSettings:
    resource: "@FrontendAdminBundle/Controller/UserSettings/"
    type:     admingenerator
    prefix:   /admin/oldal/felhasznalok-beallitasai

admin_page_school:
    resource: "@FrontendAdminBundle/Controller/School/"
    type:     admingenerator
    prefix:   /admin/oldal/iskolak

admin_page_file:
    resource: "@FrontendAdminBundle/Controller/File/"
    type:     admingenerator
    prefix:   /admin/oldal/fajlok
    
admin_login:
    pattern:  /admin
    defaults: { _controller: FrontendAdminBundle:Default:login }
    
admin_list:
    pattern:  /admin/lista
    defaults: { _controller: FrontendAdminBundle:Default:list }
    
admin_user_settings_single_show:
    pattern:   /admin/oldal/felhasznalok-beallitasai/{id}/show
    
admin_subject_single_show:
    pattern:   /admin/oldal/tantargyak/{id}/show

admin_page_subjects_u:
    pattern:   /admin/oldal/tantargyak
    
admin_page_UserSettings_u:
    pattern:   /admin/oldal/felhasznalok-beallitasai
    
admin_page_docs_u:
    pattern:   /admin/oldal/dokumentumok

admin_page_school_u:
    pattern:   /admin/oldal/iskolak

admin_page_file_u:
    pattern:   /admin/oldal/fajlok
