parameters:
#    frontend_admin.example.class: Frontend\AdminBundle\Example

services:
#    frontend_admin.example:
#        class: %frontend_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
