generator: admingenerator.generator.doctrine
params:
    i18n_catalog: Admingenerator
    model: Frontend\SubjectBundle\Entity\Subject
    namespace_prefix: Frontend
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: 
        name:
            label: Tantárgy neve
        insertDate:
            label: Létrehozás dátuma
        user:
            label: Létrehozó
        status:
            label: Aktív?
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Tantárgyak
            display: [name, insertDate, user, status]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: "Tantárgy létrehozása"
            display: [name, status]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Tantárgy szerkesztése"
            display: [name, status]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Subjects.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
