generator: admingenerator.generator.doctrine
params:
    model: Frontend\AccountBundle\Entity\UserSettings
    namespace_prefix: Frontend
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: 
        name:
            label: Név
        nickname:
            label: Nick név
        email:
            label: E-mail cím
        avatar:
            label: Aktuális avatar kép
        avatarId:
            label: Aktuális avatar kép
            formType: hidden
        gender: 
            label: Nem
        birthDate:
            label: Születési dátum
        commentText:
            label: Megjegyzés
            addFormOptions:
                attr:
                    readonly : readonly
        myUploadsVisit:
            label: Kik láthatják a feltöltéseimet
        myProfileVisit:
            label: Kik láthatják a felhasználói adataimat
        messageToMe:
            label: Kik küldhetnek nekem üzenetet
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Felhasználók a jegyzetbazison
            display: [name, avatar, gender, birthDate, commentText]
            actions:
            object_actions:
                edit: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    edit:
        params:
            title: "\"%object%\" felhasználó adatainak szerkesztése |{ %object%: UserSettings.name }|"
            display: [name, avatarId, commentText]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "\"%object%\" felhasználó adatai |{ %object%: UserSettings.name }|"
            display: [name, nickname, email, avatar, gender, birthDate, myUploadsVisit, myProfileVisit, messageToMe, commentText]
            actions:
                list: ~
                edit: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
