frontend_layout_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FrontendLayoutBundle:Default:index }

get_auth_window_ajax:
    pattern:  /ajax/azonositasi-ablak-lekerdezes
    defaults: { _controller: FrontendLayoutBundle:Header:getAuthReveal }

visit_refresh:
    pattern:  /online-statusz-frissites
    defaults: { _controller: FrontendLayoutBundle:Default:visit }

