parameters:
#    frontend_layout.example.class: Frontend\LayoutBundle\Example

services:
    frontend_user.registration.form.type:
        class: Frontend\LayoutBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: frontend_user_registration }