parameters:
#    frontend_layout.example.class: Frontend\LayoutBundle\Example

services:
#    frontend_layout.example:
#        class: %frontend_layout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
