messaging_homepage:
    pattern:  /uzenetek
    defaults: { _controller: FrontendMessagingBundle:Default:index }
    
messaging_homepage_page:
    pattern:  /uzenetek/{page}
    defaults: { _controller: FrontendMessagingBundle:Default:index }
    
messaging_more:
    pattern:  /uzenetek/{page}/tovabbi-uzenetek
    defaults: { _controller: FrontendMessagingBundle:Default:index }
