messaging_homepage:
    pattern:  /uzenetek
    defaults: { _controller: FrontendMessagingBundle:Default:index }
    
messaging_homepage_page:
    pattern:  /uzenetek/{page}
    defaults: { _controller: FrontendMessagingBundle:Default:index }
    
messaging_homepage_page_single:
    pattern:  /uzenetek/{page}/{messageId}
    defaults: { _controller: FrontendMessagingBundle:Default:index }

messaging_more:
    pattern:  /uzenetek/{page}/tovabbi-uzenetek
    defaults: { _controller: FrontendMessagingBundle:Default:index }

send_message:
    pattern:  /uzenetek/kuldes/uzenet/uj-uzenet-kuldese
    defaults: { _controller: FrontendMessagingBundle:Default:sendMessage }
    
remove_message:
    pattern:  /uzenetek/torles/uzenet/uzenet-torlese
    defaults: { _controller: FrontendMessagingBundle:Default:deleteMessage }
    
see_message:
    pattern:  /uzenetek/olvasas/uzenet/uzenetet-olvasottnak-jelolni
    defaults: { _controller: FrontendMessagingBundle:Default:seeMessage }
