parameters:
#    frontend_index.example.class: Frontend\IndexBundle\Example

services:
#    frontend_index.example:
#        class: %frontend_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
