security:login:
    pattern:  /bejelentkezes
    defaults: { _controller: FrontendAccountBundle:Auth:login }

security:registration:
    pattern:  /regisztracio
    defaults: { _controller: FrontendAccountBundle:Auth:registration }

security:forgot-pass:
    pattern:  /elfelejtett-jelszo
    defaults: { _controller: FrontendAccountBundle:Auth:forgotPass }

security:forgot-pass-activate:
    pattern:  /elfelejtett-jelszo/aktivalas/{code}
    defaults: { _controller: FrontendAccountBundle:Auth:forgotPass }

security:email-check:
    pattern:  /regisztracio/email-ellenorzes
    defaults: { _controller: FrontendAccountBundle:Auth:checkEmail }

security:nickname-check:
    pattern:  /regisztracio/nicknev-ellenorzes
    defaults: { _controller: FrontendAccountBundle:Auth:checkNickname }

settings_homepage:
    pattern:  /beallitasok/
    defaults: { _controller: FrontendAccountBundle:Settings:settingsIndex }

settings_sub_page:
    pattern:  /beallitasok/{page}.html
    defaults: { _controller: FrontendAccountBundle:Settings:settingsIndex }

change_pass_save:
    pattern:  /beallitasok/jelszo-valtoztatas/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:changePassword }

base_settings_save:
    pattern:  /beallitasok/alap-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:baseSettings }

safety_settings_save:
    pattern:  /beallitasok/biztonsagi-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:safetySettings }

avatar_settings_save:
    pattern:  /beallitasok/avatar-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:avatarSettings }

comment_settings_save:
    pattern:  /beallitasok/komment-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:comment }

profile_show:
    pattern:  /felhasznalo/{id}
    defaults: { _controller: FrontendAccountBundle:Show:index }

friends_index:
    pattern:  /baratok/
    defaults: { _controller: FrontendAccountBundle:Friends:index }

friends_add_or_remove:
    pattern:  /baratok/baratnak-jeloles-modositas
    defaults: { _controller: FrontendAccountBundle:Friends:friendsAddOrRemove }

avatar_upload_ajax:
    pattern:  /beallitasok/avatar-beallitasok/avatar-feltoltese
    defaults: { _controller: FrontendAccountBundle:Settings:uploadAvatarAjax }
