settings_homepage:
    pattern:  /beallitasok/
    defaults: { _controller: FrontendAccountBundle:Settings:settingsIndex }

settings_sub_page:
    pattern:  /beallitasok/{page}.html
    defaults: { _controller: FrontendAccountBundle:Settings:settingsIndex }

base_settings_save:
    pattern:  /beallitasok/alap-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:baseSettings }

safety_settings_save:
    pattern:  /beallitasok/biztonsagi-beallitasok/adatok-mentese
    defaults: { _controller: FrontendAccountBundle:Settings:safetySettings }
