parameters:
#    frontend_account.example.class: Frontend\AccountBundle\Example

services:
#    frontend_account.example:
#        class: %frontend_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
